### ISSUE TITLE
Module not working when product has attributes

### ISSUE THREAD

**Issue by djzwerg** [backdrop-contrib/uc_restrict_qty#1]
If the maximum quantity is defined, the customer can still order indefinitely. In my case the product has a few attributes (without adjustments).

**Comment by djzwerg** [comment]
It seems that this is the same issue like https://www.drupal.org/project/uc_restrict_qty/issues/2642708 and https://www.drupal.org/project/uc_restrict_qty/issues/2994784 and https://www.drupal.org/project/uc_restrict_qty/issues/3008250 and https://www.drupal.org/project/uc_restrict_qty/issues/3023702.

**Comment by argiepiano** [comment]
We solved this with a bit of code in a custom module as shown in this [forum post](https://forum.backdropcms.org/forum/ubercart-how-limit-number-products-type-cart). 

I think it'd be great to add this functionality to this module, namely, the ability to consider all product variations in cart as the same product. Currently this module considers each variation (defined by the different attributes chosen when adding it to the cart) a separate item. For example, see image: each item in the cart is actually the same product with a different attribute chosen. This module considers each of these as a separate product and therefore only limits the quantity per item in cart, rather than product.  I can provide a PR if you think this is a good idea, @laryn. 

<img width="882" alt="Screen Shot 2022-11-13 at 5 26 17 PM" src="https://user-images.githubusercontent.com/9938978/202481826-18e3b066-d227-44f4-a52e-edcd87d0daa8.png">

**Comment by laryn** [comment]
Absolutely -- sounds good. If you're interested in co-maintaining I'm also open to that, as I don't currently have a site that uses this.

EDIT: Feel free to update the README as part of your PR:

> Due to the way products are added to the cart, customers can add multiple variations of the same product to their carts (i.e. different attribute/option combinations) but never more than one of any given variation.

**Comment by argiepiano** [comment]
I'll give this a go soon.

**Comment by argiepiano** [comment]
@laryn, I'm fine co-maintaining (have submitted a couple of PRs for issues), but I don't use this currently. 

I have done some work on the functionality mentioned in this issue. I think it'd be best to create a new major version for this, as it needs some moderate changes in the code, but enough to merit a new major version (e.g. the new features need to change the approach from using `hook_uc_cart_item_insert` to  `uc_cart_item_presave`, etc.  

The original module is quite limited in the kinds of things it does (and some of the things it advertises don't work, for example, restricting quantity based on the SKU of product variations). I think it has the potential of being a helpful module...

Let me know your thoughts. In the meantime I'll submit a request to co-maintain

**Comment by laryn** [comment]
Sounds great @argiepiano -- thanks!

**Comment by argiepiano** [comment]
@djzwerg I have created a new dev branch, 1.x-2.x, which I intend to use to create a new major version of this module soon.

Would you be able to test the new dev branch? It adds most of what you were trying to accomplish:

- Restrict quantity by node ID, meaning that now, all variations in the cart will be counted toward the limit (before each variation was counted separately)
- Restrict quantity separately for different SKU of the same product (meaning that you can have variations that use different SKUs use different limits, counted individually) 

Additionally, both the 1.x and 2.x branches have fixed some bugs that prevented the deletion of feature settings, and also the saving of UC Restrict Quantity global settings.

Let me know if you find anything that doesn't look right.

**Comment by djzwerg** [comment]
thanks a lot @argiepiano ! Everything works fine! RTBC 👍

**Comment by argiepiano** [comment]
Thanks @djzwerg! I will close this issue now and proceed to do new releases
